# Generated by Django 6.0.3 on 2026-03-31 01:41

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs_for_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            base_slug = slugify(product.name)
            slug = base_slug
            counter = 1
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            product.slug = slug
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_order_total_amount_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.RunPython(generate_slugs_for_products),
    ]
