# Generated by Django 6.0.3 on 2026-03-31 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_product_category_choice_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
