# Generated by Django 6.0.3 on 2026-03-31 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_choice',
        ),
    ]
