# Generated by Django 6.0.2 on 2026-03-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_address_user_order_orderitem'),
        ('products', '0011_remove_category_description_remove_order_updated_at_and_more'),
    ]

    operations = [
    ]
